### ISSUE TITLE
hi, any demo ?

### ISSUE THREAD

**Issue by xgz123** [ViBiOh/fibr#1]
thanks

**Comment by mckaygerhard** [comment]
? errr user, pass ? link?

**Comment by ViBiOh** [comment]
> ? errr user, pass ? link?

Hi @mckaygerhard , I've added the [Getting started section](https://github.com/ViBiOh/fibr#getting-started) in the README when the issue was opened. I can complete for more example, what do you expect to find ?

**Comment by mckaygerhard** [comment]
hi @ViBiOh  im surprised.. you answer so fast! well in fact i openned the link at the github fibr.vibioh.fr and it ask for user adn password.. so i assume is the demo site and so only need user adn password.. also some other question but for now related to this issue only that.. : is fibr.vibioh.fr the demo site?..  and if yes.. whare are the user and pass to check it!

**Comment by ViBiOh** [comment]
Haha no, fibr.vibioh.fr is my personal instance. I understand it can be confusing, I'll remove the link.

**Comment by mckaygerhard** [comment]
got it! maybe a demo instance with reset every 10 minutes.. any way thanks @ViBiOh  i'll ask for other issues in new issue.. closing that!
