### ISSUE TITLE
how to compile, cos there's no i386 release or kfreebsd or hurd like!

### ISSUE THREAD

**Issue by mckaygerhard** [ViBiOh/fibr#143]
there's ony few releases, limits to amd64 and arm, but those hardware are industri dominated.. not so performance ones like kfreebsd, etc etc or other archs.. 

due that i need that i posted partially in **issue #97  thanks for binary deploy, great!, but is limited to amd64 and arm, there's a wide range of hardware in the market share** so a build instructions (including how to put vendos without the traditional go get) is necessary to made packages by me for others arches.. thanks in advance!

i made a build but was so rudimentary .. i will try to fix some things before post feedback here..  **that's why i asked you for doc in that topic!** i have several x32 machines and i386 ones, cos it consumes less memory and runs in any place.. (all the amd64 are 32bits also) so are cheap to deploy..

**Comment by ViBiOh** [comment]
I don't understand what kind of documentation you want on this topic. It's golang, I can cross-compile in another arch if you want, taken from [there](https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63). I limit the "by default" architectures to the ones I can reproduce behavior in case of somebody has an issue.

I can add your architecture, but I'll not be able to debug platform-specific issue on that case.

**Comment by ViBiOh** [comment]
Unless you have news on this subject, I'll close the issue by the end of week.
