### ISSUE TITLE
bug sec: user and pass visible in process list -  feat to pipe or file based auth users

### ISSUE THREAD

**Issue by mckaygerhard** [ViBiOh/fibr#145]
auth Profiles and Users are based on HTTP/Authentication basic auth.. but must parse in each run to the binary.. is there a way to use a .htpass file for?

**Comment by ViBiOh** [comment]
I don't plan to add `.htaccess` kind of features. The "share" feature is more complicated than just "password protection". With expiration time, edit rights etc.

**Comment by mckaygerhard** [comment]
> I don't plan to add `.htaccess` kind of features. The "share" feature is more complicated than just "password protection". With expiration time, edit rights etc.

oh no sorry, that's not what I mean, you confused!, **I'm talking about putting the username and _password in the invocation command line is too risky_**, instead you can read it from a flat file and that's it, I'll explain why it's a security issue:

**the command line is clearly visible in the container as well as in the process list by any other user. it is clearly a security bug** the flat file can be protected with forced permissions! this is far more secure of course!

**Comment by mckaygerhard** [comment]
that is i am talking about, a normal user also can view the command linue:

![imagen](https://user-images.githubusercontent.com/1571724/117985374-a38c7900-b306-11eb-97a5-8965cea4d0c0.png)

**Comment by mckaygerhard** [comment]
that was i talking about, not only root a normal user can view and try to gess the password:

![bug-fibr-security](https://user-images.githubusercontent.com/1571724/117985521-c585fb80-b306-11eb-8194-d7d193558932.png)

**Comment by ViBiOh** [comment]
Indeed, CLI can be risky. That's why I've added the environment variable configuration for all CLI args. In our example, you can configure the `FIBR_AUTH_USERS` env, in the `systemd` service file for example, to "hide" it.

**Comment by mckaygerhard** [comment]
wel well was a good argument to implement the feature right? :fox_face:  i have a lot more! many more! in fact i retreibved the password in a shared serverd! XD

> Indeed, CLI can be risky. That's why I've added the environment variable configuration for all CLI args. In our example, you can configure the `FIBR_AUTH_USERS` env, in the `systemd` service file for example, to "hide" it.

yeah but not all people liked systemshit XD also docker is not good for a only bare metal server.. i mean i have only one server.. deploy docker will means more system depends (python several depens) and after all then deploy a manager process and also a docker process.. is more complicated to mantain even just run the binary in a bare metal limited server 

rthis ones is enought? :full_moon_with_face:  ?

**Comment by ViBiOh** [comment]
`systemd` is an example. Starting the binary comes from a launch script (systemd, sh script, bash_history maybe), you can put the environment variable in that file (with permissions you want). It will not be visible with `ps` and the password is in a file.

My point is to have a self-sufficient binary. You point the folder, it serves the folder, based on the configuration. Requiring creating a configuration file before starting the binary is something I don't want.

At the end, you start the binary *from* a file, but the binary doesn't need to be aware of it: it reads the configuration from CLI ou env and starts.

**Comment by mckaygerhard** [comment]
umm i have more arguments but lest pause this her, i try to do the code and push a pull request.. so we can able to use both options 😑😒

**Comment by ViBiOh** [comment]
Unless you have news on this subject, I'll close the issue by the end of week.
