### ISSUE TITLE
bug: empty authorization content due DNS needs, reverse proxy does not work

### ISSUE THREAD

**Issue by mckaygerhard** [ViBiOh/fibr#147]
setup as:

```
./fibr_linux_amd64 \
  -publicURL "http://192.168.1.10:10900"  -port 10900 \
  -fsDirectory /home/data  -frameOptions "*" \
  -authProfiles "1:admin" -authUsers "1:$(htpasswd -nBb admin password1)" \
  -thumbnailVideoURL "http://192.168.1.10:10901" -thumbnailImageURL "" \
```

log:
```
2021-05-11T17:07:06-04:00 ERROR empty authorization content
2021-05-11T17:07:14-04:00 ERROR invalid credentials
```

login window popupt with basic auth but does not work, i ask:

QUESTION: using -noAtuh i can setup my own basic authentication? of course all the path will be under that.. but i can defined for specific users?

QUESTION: readme does not xplain how to manage profiles, i only can set profiles when share a file or directorio so that's why i ask the first question!

how to increase the log ? for ? i try to recompile but takes so long time and i dont have good networking

**Comment by ViBiOh** [comment]
What's the output of?

```
curl --dump-header /dev/stderr -u admin:password1 http://192.168.1.10:10900 1>/dev/null
```

With `-noAuth`, there is no credentials check. You can add you own authentification in front of fibr (with a reverse proxy, advanced firewalls etc).

Profiles are here because the `auth` library I use (my own) requires profiles but there is no propre user/profile management in fibr yet.

**Comment by mckaygerhard** [comment]
> What's the output of?
> `curl --dump-header /dev/stderr -u admin:password1 http://192.168.1.10:10900 1>/dev/null`

i property check and works now, was a confusino on reverse proxy.. now it works, but it depends on a DNS, in that command line i used a reverse proxy from `files.locanewdoamin.x` to the ip, the host were resolved only inside the server and a /etc/hosts line in the client, but noted that has some issues..

using now command line

```
./fibr_linux_amd64 \
 -publicURL "http://files.locanewdoamin.x"  -port 10900  \
  -fsDirectory /home/ftpfilesp/ -frameOptions "*"    -loggerLevel DEBUG \
 -thumbnailVideoURL "" -thumbnailImageURL "" \
  -authProfiles "1:admin" -authUsers "1:$(htpasswd -nBb admin password1)"
```
got right response :


```
Cache-Control: no-cache
Content-Language: en
Content-Security-Policy: default-src 'self'; base-uri 'self'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src 'self' data:
Content-Type: text/html; charset=UTF-8
Referrer-Policy: strict-origin-when-cross-origin
Set-Cookie: list_layout_paths=; Path=/; HttpOnly; SameSite=Strict
Strict-Transport-Security: max-age=10886400
X-Content-Type-Options: nosniff
X-Frame-Options: *
X-Permitted-Cross-Domain-Policies: none
X-Ua-Compatible: ie=edge
X-Xss-Protection: 1; mode=block
Date: Wed, 12 May 2021 17:46:36 GMT
Content-Length: 10116
Server: lighttpd/1.4.53
```

> 
> With `-noAuth`, there is no credentials check. You can add you own authentification in front of fibr (with a reverse proxy, advanced firewalls etc).
> 

that why i asked .. so the i can use "noatuh" but the ip address wil let open the files right? so .. i can combine with: ` -publicURL "http://files.locanewdoamin.x"  -port 10900`  and added `-address 127.0.0.1` to work only by the reverse proxy! using own internal authentiacion.

so for close this i set with lighttpd as:

1. run the command witn 127.0.0.1 adress listening and public url using another por, also added the frame options:

```
./fibr_linux_amd64 \
 -publicURL "http://files.locanewdoamin.x"  -port 10900  \
 -address 127.0.0.1 \
 -frameOptions "*"  \
```

2. setup the lighttpd reverse proxy that will resolve the url when domain will be resolved by the DNS cos we have a subdomain "files" under same baremetal server so:

```
$HTTP["host"] =~ "files\.locanewdoamin\.x" {
 proxy.server = ( "" => ( ( "host" => "0.0.0.0", "port" => "10900" ) ) )
}
```

3. later for each route under "files.locanewdoamin.x" we must setup a basic auth in the lighttpd webserver of course that provicdes many options for.

> Profiles are here because the `auth` library I use (my own) requires profiles but there is no proper user/profile management in fibr yet. Fibr is here mainly for personnal use and not be a Dropbox/GoogleDrive/YouNameIt replacement.

due that limitation (fake profiles) i setup this, and i will added later a more separated configuration for multiple users over various directories.. 

a last question after closing: in this way, sharing password will be independent of the auth routes? not right? **so how can i disable shared passwords?** or how to handle this in my paths, cos those are under webserver protective way of course.
