### ISSUE TITLE
feat req / bug - no templates anymore, no customized interface ui

### ISSUE THREAD

**Issue by mckaygerhard** [ViBiOh/fibr#151]
since feature of embebed fs templates of commit 21b9b2bc1873f74380a05d5db8c2fcabf9dd58c4 now two problems comes:

1. impossible to customized cos all the interface html are embebed
2. golang raized to 1.16 for build

so well its impossible to perform a customized interface ..

**Comment by ViBiOh** [comment]
Why bumping to go 1.16 is a problem? In the release, I provide a self-sufficient binary.

For customized interface, the idea with embed is to have, again, a self-sufficient binary with no external dependencies/folder, etc.

**Comment by mckaygerhard** [comment]
> For customized interface, the idea with embed is to have, again, a self-sufficient binary with no external dependencies/folder, etc.

yes pretty understand..but there's no option to customized XD .. of course this is not a high priority feature request.. cos simplicity is the main purpose! 


> Why bumping to go 1.16 is a problem? In the release, I provide a self-sufficient binary.

yeah.. but as i post before.. customize templates or UI will require rebuild that will require last golang that will require more up to date system etc etc.. i dont like to rise the depends to develop in my systems.. (common problem is that will end in hardware not working anymore if are too long or older) and i work with many older hardware (many many amount of devices)

**Comment by ViBiOh** [comment]
It reminds me a [famous XKCD problems](https://xkcd.com/1172/) 😅

If you want a customized interface for this, I advice you to fork the project. Embed.FS is a great addition in go1.16 for embedding templates in a clean way.

**Comment by mckaygerhard** [comment]
> If you want a customized interface for this, I advice you to fork the project. Embed.FS is a great addition in go1.16 for embedding templates in a clean way.

yes understood that's why i posted that is not high priority request and simplicity is main purpose! XD

> It reminds me a [famous XKCD problems](https://xkcd.com/1172/) sweat_smile

XD

**Comment by mckaygerhard** [comment]
is theere a way to avoid golang 1.16 and use 1.14 ? there's a binddata way to do.. in any case.. well in fact i want the old behaviour.. for a one particular case, rest of my usage is fine with binaries

**Comment by ViBiOh** [comment]
According to [Golang version policy](https://golang.org/doc/devel/release#policy) this version is no longer supported, so no, I'll not provide Go 1.14 support. I'm trying to follow new versions in order to avoid too much technical debt.

Feel free to fork it if you have very custom usage, that why this project is open-sourced and how open-source works from my point of view. I'm working on it mostly for pleasure, first suited to my needs but trying to cover the most cases. I'm open to improve it but I can't support every user particular cases.

**Comment by ViBiOh** [comment]
Unless you have news on this subject, I'll close the issue by the end of week-end.
