### ISSUE TITLE
Infinite lists scrolling (in)efficiency (i.e. loading on demand)

### ISSUE THREAD

**Issue by dumblob** [ViBiOh/fibr#320]
Newbie here. I wonder if the web listing (especially images/videos) support "infinite scrolling back & forth"?

Web browsers choke if there are more than ~7 pages of picture content to be scrolled through. As a "solution" (actually a nasty workaround but widely adopted - incl. Google, React, etc.) is to completely remove all invisible DOM elements from the DOM and instead put there one and only one block element of the same dimensions as all the removed elements together.

**Comment by ViBiOh** [comment]
Hi @dumblob ,

Sorry I'm a bit late on this, I didn't get the notification and I do spring cleaning right now!

I know that throwing all the DOM elements at once in the same page is not very efficient for browser performance, but avoiding JS framework is a deliberate choice for this project. The thumbnails for an entire folder are streamed and injected in the DOM directly. Changing to have some lazy loading require a lot of work to rethink the way I retrieve these thumbnails.

Splitting your images into folder can be a solution on your side.
