### ISSUE TITLE
Files can't upload over wifi network

### ISSUE THREAD

**Issue by kcubeterm** [ViBiOh/fibr#69]
I opened fibr server in termux,(phone A). my second (phone B)was connected with it by hotspots, 
### configuration
```
fibr  -address 0.0.0.0 -port 8081 -noAuth   -templates "/data/data/com.termux/files/home/fibr/templates/" -fsDirectory "/data/data/com.termux/files/home/fibr_store" -csp "default-src 'self'; base-uri 'self'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src 'self' data:"
```

I browse http://192.168.43.1:8081 , and able to download Content, but I can't upload with phone B

When I browse http://192.168.43.1:8081 , same , I can't upload with phone A also

But I can file with only localhost, http://localhost:8081

I think , must be any config issue,

**Comment by ViBiOh** [comment]
Hi @kcubeterm,

Thank you for your interest in `fibr` =)

Can you browse from "Phone B" even if it's not an upload ? The upload takes the same path as anything else, it seems strange to me.

Have you an error message on the server side or the client side?

On the server side, your address is an IPv4, both phones are on the same network with the same IP protocol?

On the client side, it relies on some new thing in browsers, like [async/await](https://github.com/ViBiOh/fibr/blob/master/templates/upload-form.html#L43), are you using [a compatible browser](https://caniuse.com/#feat=async-functions) on both phones?

**Comment by kcubeterm** [comment]
I solved it by csp , -csp script-src self, solved my issues,
