### ISSUE TITLE
Why fibr is slower than exepection over wifi network ?

### ISSUE THREAD

**Issue by kcubeterm** [ViBiOh/fibr#70]
I guess this must be cause of security layer,

**Comment by ViBiOh** [comment]
Fibr relies on basics of HTTP for all the things. I've never experienced slow browse or upload.

Upload is progressive with [the help of XMLHttpRequest](https://github.com/ViBiOh/fibr/blob/master/templates/upload-form.html#L161). The counterpart is that it opens a new connections for every uploaded file (with SSL handshake, basic auth, and so on). I'm using [a custom multipart reader for upload](https://github.com/ViBiOh/fibr/blob/master/pkg/crud/post.go#L82) in order to avoid loading file in memory (for large videos, by example)

Authentication is made with [HTTP Basic and an in-memory state](https://github.com/ViBiOh/fibr/blob/master/pkg/fibr/fibr.go#L68), so everything should be fast.

What order of bandwith degradation do you see ?

**Comment by kcubeterm** [comment]
> What order of bandwith degradation do you see ?
I expect atleast 3 mb/s, even python http server provide 3 to 5 mb/s, and with ftp I get 11 mb/s download speed, but with fibr I didn't see that speed,  fibr gives 1 mb/s.

I have a golang program written by self gives 3.6 mb/s.

**Comment by ViBiOh** [comment]
When files are uploaded, they are directly written to the disk, via an io pipe. There is no memory bufferization [other that que 32kb copy](https://github.com/ViBiOh/fibr/blob/master/pkg/crud/upload.go#L45).

Check your disk write speed

```bash
sync; dd if=/dev/zero of=tempfile bs=1M count=1024; sync
rm tempfile
```

I've checked with my personnal instance with my cellular connection shared with my laptop.

```
> sync; dd if=/dev/zero of=tempfile bs=1M count=1024; sync
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB, 1.0 GiB) copied, 2.50657 s, 428 MB/s
```

I have a download speed of 10Mb/s, so the limitation is on the network, not the disk.

```bash
> curl -q -4 -o /tmp/100M.iso https://bouygues.testdebit.info/100M.iso
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 95.3M  100 95.3M    0     0  10.3M      0  0:00:09  0:00:09 --:--:-- 11.3M
```

I have an upload speed of 1Mb/s

```bash
> curl -q -4 -o /dev/null -F "filecontent=@/tmp/100M.iso" https://bouygues.testdebit.info
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 95.4M  100 95185  100 95.3M    989  1015k  0:01:36  0:01:36 --:--:--  718k
```

I have near the same upload speed when upload to `fibr`

```bash
> curl -q -4 -u "MY_SECRET_CREDENTIALS" -o /dev/null https://fibr.vibioh.fr/ -F file=@/tmp/100M.iso -F method=POST
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 95.3M    0     0  100 95.3M      0  1137k  0:01:25  0:01:25 --:--:-- 1123k
```

I have near the same download speed with `fibr`

```
> curl -q -4 -u "MY_SECRET_CREDENTIALS" -o /dev/null https://fibr.vibioh.fr/100m.iso
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 95.3M  100 95.3M    0     0  10.7M      0  0:00:08  0:00:08 --:--:-- 12.1M
```

I've ran a test with the upload modal from the browser. I don't have exact metrics, but it takes me 1min 20 to upload files with the progress bar, so it's approximately the same.

Can you run those checks too on your side to see if there any difference ?

I'm in France, so you may have more accurate speed tester than `bouygues.testdebit.info`.

**Comment by kcubeterm** [comment]
> I have a download speed of 10Mb/s, so the limitation is on the network, not the disk.

Yea, you are right,  that was network limitation.

One more question. Can I disable -csp , has any options available or have to recompile manually

**Comment by ViBiOh** [comment]
> One more question. Can I disable -csp , has any options available or have to recompile manually

Pass a blank option to the CSP: `-csp ''` It will send an empty header and browsers don't take care of it.

**Comment by kcubeterm** [comment]
Thankyou :)
