### ISSUE TITLE
[Feature Request] Copy,Cut,Paste,Rename

### ISSUE THREAD

**Issue by varbhat** [ViBiOh/fibr#75]
Hey ViBiOh,
Thanks for this amazing file browser and manager which I have installed and am liking it.

But,it has no copy,cut,paste,rename . Can you add these features to the file manager?

Another feature that I would like to have is downloading the file from the URL . If this is installed in multiuser environment and ssh access to each user is not given and user needs to download file from URL,it is desirable feature to download files from url within file manager.

I would recommend you to take look at [grab](https://github.com/cavaliercoder/grab) for implementing downloader feature.

**Comment by ViBiOh** [comment]
hi @varbhat 

Thank you for message, glad you are happy with fibr :)

There is a rename feature, you must have edit right and click on the pencil icon (on hover)

![Screen Shot 2020-08-07 at 11 25 05 AM](https://user-images.githubusercontent.com/2349470/89631280-dcdc1800-d8a0-11ea-9355-189b696e4d07.png)

For Copy/Cut/Paste, are you expecting a feature like a `mv` command (for moving to another folder) ?

You can already download the file from URL.

When you browse with ui, the URL is suffixed with `?browser` query string for rendering UI. But if you omit that query param (e.g. http://fibr.domain/my_filename.jpg) it's the plain file read from disk.

Also, there is a download button on each file or folder (see capture). For files, it downloads the file directly, for folder, it streams you the folder content into a zip.

**Comment by varbhat** [comment]
Hey @ViBiOh ,

Rename and Delete option didn't show before because I had forgot to set `-authProfiles` .Now,they are showing properly like it is in the screenshot.

_> For Copy/Cut/Paste, are you expecting a feature like a mv command (for moving to another folder) ?_

**YES**

_> You can already download the file from URL._ 

I am not talking about downloading file from fibr to machine by direct link. Direct link and Share links are implemented properly and I am thankful for it.

What I was talking about is downloading file by URL to my fibr instance remotely. I find a link that I would like to download to my remote machine. I would like to do it in fibr itself. I would suggest you to add small url box to Upload button(#upload-modal) where we can specify direct url . fibr then must download file from that direct url to the specified directory.In short,it must be remote file downloader which downloads the file to the specified directory.

**Comment by ViBiOh** [comment]
Implementing `move` can be tricky with the `../` pattern, with inexistant folders, and so on, but I can give it a try ;)

For uploading from an URL directly, I have to look carefully what's possible for avoiding undesired behaviors:
- define a http timeout for download/upload (user-defined on upload or configured globally on API)
- how to avoid storing it on memory (connecting http.Response to io.writer by example)
- uploading from URL can be synchronous (UI wait for completion, but there is HTTP Timeout) or asynchronous with a queue of work (but there is a new dependencies for an AMQP-like broker, in order to respect 12factor)

Not a trivial one!

**Comment by varbhat** [comment]
Hey @ViBiOh ,

I think that you can use https://github.com/cavaliercoder/grab for file "Upload from URL" feature .  For new download , you just create new client ,and for that client you send new request with path and url and it will proceed with download. Each client runs in own Goroutine too.

And `../` pattern is not really necessary . If that is little difficult,you can try absolute path where you specify path from the fibr root directory

**Comment by varbhat** [comment]
Any update on download manager support? i mean "remote url download"

tinyfilemanager , php script has it

**Comment by ViBiOh** [comment]
Hi @varbhat 

For the remote download, I didn't have the time to focus on it yet. From my point of view, it needs:
* a new view for managing running downloads (context, list, etc)
* a deeper look at how to gracefully shutdown the server if there are running downloads.
  * the library you point seems to be able to stop/resume. So I have to store the download informations somewhere (maybe the `.fibr/.json` file, but it's not designed for it yet)
* update the existing upload form to accept URL

If you want it as soon as possible, you can pipe wanted download to fibr

```bash
curl https://YOUR_WANTED_FILE | curl -u "admin:admin" -H "Accept: text/plain" http://localhost:1080/your_folder/ --form method=POST -form file=@-
```

It will upload the file with name `-` (not optimal) but does that you want
